sonar.projectKey=onigoetz_anypack-plugin-serve
sonar.organization=onigoetz
sonar.projectName=anypack-plugin-serve

sonar.sources=anypack-overlay/src,rspack-nano/lib,plugin/lib
sonar.tests=anypack-overlay/test,rspack-nano/test,plugin/test

sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
